services:
  database:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: mys1mpl3p@ssw0rd
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - db_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080
    networks:
      - db_network
    environment:
      ADMINER_DEFAULT_SERVER: database

volumes:
  db_data:

networks:
  db_network:
