services:
  database:
    image: 'postgres:latest'
    restart: always
    shm_size: 128mb
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - 5432:5432
    volumes:
        - notifications_db_data:/var/lib/postgresql/data
    networks:
        - notifications_db_net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080
    networks:
      - notifications_db_net
    environment:
      ADMINER_DEFAULT_SERVER: database

volumes:
  notifications_db_data:

networks:
  notifications_db_net:
